=== alt-ee/swengproject/target/test-classes/PWS_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:slideshow.Namespace"
           xmlns="urn:slideshow.Namespace"
           elementFormDefault="qualified">

    <xs:element name="slideshow">
        <xs:annotation>
            <xs:documentation>
            Note: i) All coordinates represent the top-left corner of the object in question. 
			ii) All URLs (typically 'urlname') are absolute or relative to current URL. 
			iii) All colours are represented by a string of the form '#ffffff' where each pair of characters after the hash are the hexadecimal representation of red, green, blue respectively.
        </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="defaults">
                    <xs:annotation>
                        <xs:documentation>
                            Default look and feel for slides - these elements should be applied by default to all slides.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="backgroundcolour" type="RGBColour" use="required"/>
                        <xs:attribute name="font" type="xs:string" use="required"/>
                        <xs:attribute name="fontsize" type="xs:int" use="required"/>
                        <xs:attribute name="fontcolour" type="RGBColour" use="required"/>
                        <xs:attribute name="linecolour" type="RGBColour" use="required"/>
                        <xs:attribute name="fillcolour" type="RGBColour" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="slide" minOccurs="1" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                        An individual slide
                    </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="text" type="TextType"/>
                            <xs:element name="line" type="LineType"/>
                            <xs:element name="shape" type="ShapeType"/>
                            <xs:element name="audio" type="AudioType"/>
                            <xs:element name="image" type="ImageType"/>
                            <xs:element name="video" type="VideoType"/>
                            <xs:element name="button" type="ButtonType"/>
                        </xs:choice>
                        <xs:attribute name="id" type="xs:string" use="required">
                            <xs:annotation>
                                <xs:documentation>
                                    ID for this slide - could be used to leap around slideshow.
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="duration" type="xs:int">
                            <xs:annotation>
                                <xs:documentation>
                                    Period (in secs) for which this slide should be displayed.
                                    If not set then slide should be displayed until navigated away from (e.g. with a button)
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="author" type="xs:string"/>
            <xs:attribute name="version" type="xs:string"/>
            <xs:attribute name="comment" type="xs:string"/>
        </xs:complexType>
    </xs:element>    
    
    <xs:simpleType name="RGBColour">
        <xs:annotation>
            <xs:documentation>
                String type restricted to only accept hexadecimal values #000000 to #ffffff
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="#(([0-9]|[a-f]){6})"/>
       </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TextType" mixed="true">
        <xs:annotation>
            <xs:documentation>
                Some text to be drawn, can contain any number of b or i tags to denote bold or italic text.
                If font, fontsize or fontcolour aren't set then value from defaults should be used
                If duration is not set then should be displayed as long as slide is shown
            </xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="b" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Encapsulates bold text
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="i" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Encapsulates italic text
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
        <xs:attribute name="font" type="xs:string" />
        <xs:attribute name="fontsize" type="xs:int" />
        <xs:attribute name="fontcolour" type="RGBColour" />
        <xs:attribute name="xstart" type="xs:int" use="required" />
        <xs:attribute name="ystart" type="xs:int" use="required" />
        <xs:attribute name="duration" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="LineType">
        <xs:annotation>
            <xs:documentation>
                A Line to be drawn
                If linecolour is not set then value from defaults should be used
                If duration is not set then should be displayed as long as slide is shown
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="xstart" type="xs:int" use="required"/>
        <xs:attribute name="ystart" type="xs:int" use="required"/>
        <xs:attribute name="xend" type="xs:int" use="required"/>
        <xs:attribute name="yend" type="xs:int" use="required"/>
        <xs:attribute name="linecolour" type="RGBColour"/>
        <xs:attribute name="duration" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="ShapeType">
        <xs:annotation>
            <xs:documentation>
                A shape to be drawn
                If fillcolour is not set then value from defaults should be used
                If duration is not set then should be displayed as long as slide is shown
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="shading" type="ShadingType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="oval"/>
                    <xs:enumeration value="rectangle"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="xstart" type="xs:int" use="required"/>
        <xs:attribute name="ystart" type="xs:int" use="required"/>
        <xs:attribute name="width" type="xs:int" use="required"/>
        <xs:attribute name="height" type="xs:int" use="required"/>
        <xs:attribute name="fillcolour" type="RGBColour"/>
        <xs:attribute name="duration" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="ShadingType">
        <xs:annotation>
            <xs:documentation>
                If present, specifices a gradient fill. Parameters are as described in java.awt.GradientPaint
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="x1" type="xs:int" use="required"/>
        <xs:attribute name="y1" type="xs:int" use="required"/>
        <xs:attribute name="colour1" type="RGBColour" use="required"/>
        <xs:attribute name="x2" type="xs:int" use="required"/>
        <xs:attribute name="y2" type="xs:int" use="required"/>
        <xs:attribute name="colour2" type="RGBColour" use="required"/>
        <xs:attribute name="cyclic" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:complexType name="AudioType">
        <xs:annotation>
            <xs:documentation>
                Some audio to be played, either .wav or .au 
            </xs:documentation>
        </xs:annotation>

        <xs:attribute name="urlname" type="xs:anyURI" use="required"/>
        <xs:attribute name="starttime" type="xs:int">
            <xs:annotation>
                <xs:documentation>
                    Number of seconds audio should start playing after slide is loaded
                    If not set then a button should be used to control playback
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="loop" type="xs:boolean" use="required">
            <xs:annotation>
                <xs:documentation>
                    Whether the audio should loop for the current slide
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ImageType">
        <xs:annotation>
            <xs:documentation>
                An image to be displayed, either GIF or JPEG
                If duration is not set then should be displayed as long as slide is shown
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="urlname" type="xs:anyURI" use="required"/>
        <xs:attribute name="xstart" type="xs:int" use="required"/>
        <xs:attribute name="ystart" type="xs:int" use="required"/>
        <xs:attribute name="width" type="xs:int" use="required"/>
        <xs:attribute name="height" type="xs:int" use="required"/>
        <xs:attribute name="duration" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="VideoType">
        <xs:annotation>
            <xs:documentation>
                A video to be played
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="urlname" type="xs:anyURI" use="required"/>
        <xs:attribute name="starttime" type="xs:int">
            <xs:annotation>
                <xs:documentation>
                    Number of seconds video should start playing after slide is loaded
                    If not set then a button should be used to control playback
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="loop" type="xs:boolean" use="required">
            <xs:annotation>
                <xs:documentation>
                    Whether the video should loop for the current slide
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="xstart" type="xs:int" use="required"/>
        <xs:attribute name="ystart" type="xs:int" use="required"/>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ButtonType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="text">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="font" type="xs:string" />
                                <xs:attribute name="fontsize" type="xs:int" />
                                <xs:attribute name="fontcolour" type="RGBColour" />                            
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="image">
                    <xs:complexType>
                        <xs:attribute name="urlname" type="xs:anyURI" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:choice>
                <xs:element name="slideid" type="xs:string"/>
                <xs:element name="mediaid" type="xs:string"/>
            </xs:choice>            
        </xs:sequence>   
        <xs:attribute name="xstart" type="xs:int" use="required"/>
        <xs:attribute name="ystart" type="xs:int" use="required"/>
        <xs:attribute name="width" type="xs:int" use="required"/>
        <xs:attribute name="height" type="xs:int" use="required"/>         
    </xs:complexType>


</xs:schema>

=== alt-ee/swengproject/src/test/resources/PWS_example.xml
<?xml version="1.0" encoding="UTF-8"?>

<slideshow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="urn:slideshow.Namespace"
           xsi:schemaLocation="urn:slideshow.Namespace PWS_Schema.xsd"
           author="alex tee" comment="example file" version="1.0">
    <defaults backgroundcolour="#43675a" font="Calibri" fontsize="16" fontcolour="#a6aeae" linecolour="#f2c95e" fillcolour="#6dcbdb" />

    <slide id="slide01">
        <text xstart="100" ystart="200">test text <b>some bold text</b> <i>some italic text</i> <b>some more bold text</b> some normal text</text>
        <line xstart="40" ystart="20" xend="80" yend="20"/>
        <shape type="oval" xstart="10" ystart="10" width="20" height="34" duration="10">
            <shading x1="0" y1="0" colour1="#f2a54b" x2="0" y2="0" colour2="#dd452a" cyclic="false"/>
        </shape>
        <text xstart="7" ystart="34" font="Joker">more test text with specified font</text>
        <image urlname="resources/images/image.png" xstart="10" ystart="10" width="5" height="6"/>
    </slide>

    <slide id="slide02" duration="100">
        <video urlname="resources/videos/video.mp4" loop="true" xstart="20" ystart="9" id="testVideo" />
        <audio urlname="resources/audio/audio.wav" loop="true" starttime="10"/>
    </slide>
</slideshow>
